---
title: Data Structure
---
flowchart LR
    subgraph xdataset
        direction LR
        d_name[name]
        subgraph xndarray_1
            direction TB
            nda_name[name +\n <i>add_name</i>]
            subgraph ndarray
                direction TB
                D[<i>NTVtype</i>]
                A[darray\n or URI]
                B[<i>shape</i>]
                class A da
            end
            B1[<i>links</i>]
            D1[<i>meta</i>]
            class ndarray nda
        end
        other[<b>#149;#149;#149;</b>]
        subgraph xndarray_n
            direction LR
        end
        class xndarray_1,xndarray_n xnda
        class other attributes
    end
    class xdataset dataset
    classDef attributes fill:#bbf,stroke:#f6,stroke-width:1px,color:#000,stroke-dasharray: 0 5
    classDef xnda fill:#99d,stroke:#009,stroke-width:2px,color:#808
    classDef nda  fill:#77b,stroke:#00e,stroke-width:2px,color:#808
    classDef da  fill:#55b,stroke:#00e,stroke-width:2px,color:#fff
    classDef dataset stroke:#007,fill:#bbf,color:#808